# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0002_remove_videoupload_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.Category'),
        ),
    ]
